;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here
e.=explorer .
gl=git log --oneline --all --graph --decorate  $*
ls=ls --show-control-chars -F --color $*
pwd=cd
clear=cls
history=cat "%CMDER_ROOT%\config\.history"
unalias=alias /d $1
vi=vim $*
cmderr=cd /d "%CMDER_ROOT%"
np=%HOMEPATH%\Notepad++\notepad++.exe
vimpath=cd %HOMEPATH%\documents\cmder\vendor\git-for-windows\usr\share\vim
cmderpath=cd %HOMEPATH%\documents\cmder
python=C:\ProgramData\Anaconda3\python.exe 
home=cd %HOMEPATH%\Documents
vpigestao= cd C:\server\projetos\projetos_vpigestao
gestaopessoas= cd C:\server\projetos_vpi\projeto_gestaopessoas
gestaoativos= cd C:\server\projetos_vpi\projeto_gestaoativos
htdocspath= cd C:\server\htdocs
phppath=cd C:\server\php
